### ISSUE TITLE
No longer works on Sonarr v3

### ISSUE THREAD

**Issue by SeanPM5** [custom-components/sensor.sonarr_upcoming_media#34]
**Describe the Bug**
First off, happy to see this integration (and the upcoming media card) maintained! The new deep link support looks very cool.

I use Sonarr v3 (3.0.10.1567) and cannot upgrade to Sonarr v4 currently. The more recent commits that added support for Sonarr v4 do not appear to be backwards compatible, it broke this integration on Sonarr v3 unfortunately. 

The sensor returns a state of "Online" but doesn't populate with any shows.  I tested the link in troubleshooting section and it returned the JSON of upcoming shows successfully in the browser. I then rolled back to the old `sensor.py` file from Dec 14, 2021 (prior to the PR that added Sonarr v4 support) and it works fine again.

**Indicate if you followed all steps in the [troubleshooting doc](https://github.com/custom-cards/upcoming-media-card/blob/master/troubleshooting.md)**
Yes

**What data does the sensor display if any?**
```
sensor.sonarr_upcoming_media
Sonarr_Upcoming_Media

Online	

data: 
- title_default: $title
  line1_default: $episode
  line2_default: $release
  line3_default: $rating - $runtime
  line4_default: $number - $studio
  icon: mdi:arrow-down-bold

friendly_name: Sonarr_Upcoming_Media
```

**Does the default Home Assistant Sonarr component work for you?**
Yes

**Home Assistant Version**
2024.4.0b4
